# Copyright 2024-2025 DavoCoder
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# response_post_processor_interface.py
from abc import ABC, abstractmethod

class ResponsePostProcessor(ABC):
    """
    Abstract class for post-processing the LLM-generated response.
    """

    @abstractmethod
    def process(self, response: str, retrieved_docs: list) -> str:
        """
        Process the LLM-generated response.

        Args:
            response (str): The raw response generated by the LLM.
            retrieved_docs (list): A list of documents used for generating the response.

        Returns:
            str: The processed response.
        """
        pass
